// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZutWctO3W1gS4QMENO3zvthxaFKqJQk',
    appId: '1:531464333470:web:238623a67660339978b38f',
    messagingSenderId: '531464333470',
    projectId: 'ilona-zakovits',
    authDomain: 'ilona-zakovits.firebaseapp.com',
    storageBucket: 'ilona-zakovits.firebasestorage.app',
    measurementId: 'G-JBKE7TNKBE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1iO8Y9sQlAS86abjRgR5PUnbNAOCrGh8',
    appId: '1:531464333470:ios:c16bec1917de5f3b78b38f',
    messagingSenderId: '531464333470',
    projectId: 'ilona-zakovits',
    storageBucket: 'ilona-zakovits.firebasestorage.app',
    iosBundleId: 'com.example.routefitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1iO8Y9sQlAS86abjRgR5PUnbNAOCrGh8',
    appId: '1:531464333470:ios:c16bec1917de5f3b78b38f',
    messagingSenderId: '531464333470',
    projectId: 'ilona-zakovits',
    storageBucket: 'ilona-zakovits.firebasestorage.app',
    iosBundleId: 'com.example.routefitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB73cLyVct3g3yHu0iNblxyyLG50LUVvXM',
    appId: '1:531464333470:web:b17570663e70408978b38f',
    messagingSenderId: '531464333470',
    projectId: 'ilona-zakovits',
    authDomain: 'ilona-zakovits.firebaseapp.com',
    storageBucket: 'ilona-zakovits.firebasestorage.app',
    measurementId: 'G-H8K1NTY4S1',
  );
}
