#!/bin/bash
# Path to your .env file
ENV_FILE="../.env"
# Path to the output config file
OUTPUT_FILE="Flutter/Keys.xcconfig"

echo "// This file is automatically generated from .env" > $OUTPUT_FILE

if [ -f "$ENV_FILE" ]; then
  # Extract GOOGLE_MAPS_API_KEY and append to xcconfig
  grep "GOOGLE_MAPS_API_KEY" $ENV_FILE >> $OUTPUT_FILE
  echo "Updated Keys.xcconfig from .env"
else
  echo "Warning: .env file not found at $ENV_FILE"
fi
